# Generated by Django 4.2.2 on 2023-06-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
