# Generated by Django 4.2.2 on 2023-06-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_date',
            field=models.DateField(auto_now_add=True, default='1998-01-01'),
            preserve_default=False,
        ),
    ]
