# Generated by Django 4.2.2 on 2023-06-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_task_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user',
        ),
    ]
