# Generated by Django 4.2.2 on 2023-06-19 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
