# Generated by Django 4.2.2 on 2023-06-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
