# Generated by Django 4.2.2 on 2023-06-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
